### ISSUE TITLE
String.prototype.replace called on null for replace.call for npm build for RSS

### ISSUE THREAD

**Issue by rajks24** [timlrx/pliny#103]
**Describe the bug**
I am getting error for npm build operation on integration of this template and building the site.

**To Reproduce**
1. Run the Build with the cmd

**Expected behavior**

```
$ npm run build                                                                                                       

> starter-blog@0.0.1 build
> cross-env INIT_CWD=$PWD next build && cross-env NODE_OPTIONS='--experimental-json-modules' node -r esbuild-register ./scripts/postbuild.mjs
```

**Error :**
```
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

(node:53292) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
RSS feed generated...
file:///app-next/node_modules/pliny/chunk-ECOO6QVZ.js:12
var escape = (es) => replace.call(es, ca, pe);
                             ^

TypeError: String.prototype.replace called on null or undefined
    at replace (<anonymous>)
    at escape (file:///app-next/node_modules/pliny/chunk-ECOO6QVZ.js:12:30)
    at generateRss (file:///next-proj/app-next/node_modules/pliny/utils/generate-rss.js:21:16)
    at generateRSS (file:///next-proj/app-next/node_modules/pliny/utils/generate-rss.js:36:17)
    at rss (file:///app-next/scripts/rss.mjs:6:3)
    at postbuild (file:///next-proj/app-next/scripts/postbuild.mjs:6:22)
    at file:///app-next/scripts/postbuild.mjs:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0
```

**System Info (if dev / build issue):**
 - OS: Mac
 - Node version (please ensure you are using 14+) node: '18.13.0'
 - Npm version npm: '8.19.3'

**Browser Info (if display / formatting issue):**
- Version template version - "pliny": "0.0.10"

**Additional context**
i checked the content of the chunk,  and sharing as below :
```
// src/utils/htmlEscaper.ts
var { replace } = "";
var ca = /[&<>'"]/g;
var esca = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  "'": "&#39;",
  '"': "&quot;"
};
var pe = (m) => esca[m];
var escape = (es) => replace.call(es, ca, pe);

export { escape };
```

**Comment by timlrx** [comment]
I decided to add the RSS function directly to the blog template itself and not maintain a separate utility function over here. I think this makes it easier to customize. Will close this issue since it is no longer relevant.
