### ISSUE TITLE
Cannot deploy to Edge servers. 

### ISSUE THREAD

**Issue by bskimball** [timlrx/pliny#139]
Tried both Vercel and Cloudflare pages. Below is the error received when trying to access a page using MDX. 

```
EvalError: Code generation from strings disallowed for this context
    at (node_modules/pliny/mdx-components.js:9:13)
    at (node_modules/pliny/mdx-components.js:13:29)
    at (node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:28:35)
    at (node_modules/next/dist/compiled/react/cjs/react.shared-subset.production.min.js:29:98)
    at (node_modules/pliny/mdx-components.js:13:9)
    at (node_modules/pliny/mdx-components.js:17:14)
    at (node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:41:208)
    at (node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:46:158)
    at (node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:37:180)
```

**Comment by bskimball** [comment]
Looks like an issue with the useMDXComponent from ContentLayer

**Comment by TheAlphamerc** [comment]
Getting same issue on Vercel. Is there any solution of this

**Comment by bskimball** [comment]
@TheAlphamerc I just run the site as SSG

**Comment by vioao** [comment]
@bskimball How do you solve the problem?
