### ISSUE TITLE
When deploying to Vercel, I get this error of no declared member

### ISSUE THREAD

**Issue by OhYello** [timlrx/pliny#84]
![Declared function](https://user-images.githubusercontent.com/121548861/209795214-180a4698-6362-4f09-90ab-c7ed0e5659e8.png)

In this screenshot I declared the function and when I try to deploy it to Vercel I get this error message.

![Vercel Error Message](https://user-images.githubusercontent.com/121548861/209795009-36ae875f-f9cc-4519-ab37-87afcdfc9845.png)

Any help would be greatly appreciated, fairly new to programming so not sure what or how to fix this issue.

**Comment by bravo-kernel** [comment]
Any updates on this, getting a similar error:

```
[09:25:11.512] TypeError: String.prototype.replace called on null or undefined
[09:25:11.513]     at replace (<anonymous>)
[09:25:11.513]     at escape (file:///vercel/path0/node_modules/pliny/chunk-ECOO6QVZ.js:12:30)
[09:25:11.513]     at generateRss (file:///vercel/path0/node_modules/pliny/utils/generate-rss.js:23:22)
[09:25:11.513]     at generateRSS (file:///vercel/path0/node_modules/pliny/utils/generate-rss.js:36:17)
[09:25:11.513]     at rss (file:///vercel/path0/scripts/rss.mjs:6:3)
[09:25:11.513]     at postbuild (file:///vercel/path0/scripts/postbuild.mjs:6:22)
[09:25:11.513]     at file:///vercel/path0/scripts/postbuild.mjs:9:1
[09:25:11.513]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[09:25:11.513]     at async Promise.all (index 0)
[09:25:11.513]     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

**Comment by timlrx** [comment]
Sorry for the late reply, but the latest version works without issue. You can see an example at https://github.com/timlrx/test-deployment. Let me know if you run into further problems?

**Comment by bravo-kernel** [comment]
No worries, I appreciate the effort. I will take a look in the coming days and will report back 💃

**Comment by OhYello** [comment]
Looks like it's fixed, but now I'm seeing another issue from the example.

`Warning: data for page "/blog/[...slug]" (path "/blog/new-features-in-v1") is 278 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.`

**Comment by bravo-kernel** [comment]
@OhYello that's not an error, just a **warning** that the content of the page is quite large. Feel free to close this issue.
