### ISSUE TITLE
Vercel deployment fails with TypeError related to RSS

### ISSUE THREAD

**Issue by bravo-kernel** [timlrx/pliny#87]
Vercel deployment fails with below error, using latest Pliny:

```
[09:25:11.512] TypeError: String.prototype.replace called on null or undefined
[09:25:11.513]     at replace (<anonymous>)
[09:25:11.513]     at escape (file:///vercel/path0/node_modules/pliny/chunk-ECOO6QVZ.js:12:30)
[09:25:11.513]     at generateRss (file:///vercel/path0/node_modules/pliny/utils/generate-rss.js:23:22)
[09:25:11.513]     at generateRSS (file:///vercel/path0/node_modules/pliny/utils/generate-rss.js:36:17)
[09:25:11.513]     at rss (file:///vercel/path0/scripts/rss.mjs:6:3)
[09:25:11.513]     at postbuild (file:///vercel/path0/scripts/postbuild.mjs:6:22)
[09:25:11.513]     at file:///vercel/path0/scripts/postbuild.mjs:9:1
[09:25:11.513]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[09:25:11.513]     at async Promise.all (index 0)
[09:25:11.513]     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

**To Reproduce**
1. Generate a new Pliny app
2. Deploy to Vercel
3. See error

**Workaround**
Vercel deployment will succeed after making these changes:

1. Disable RSS in `components/SEO.tsx`:
  
    ```
      {/* <Head>
        <link
          rel="alternate"
          type="application/rss+xml"
          title={`${description} - RSS feed`}
          href={`${siteMetadata.siteUrl}${router.asPath}/feed.xml`}
        />
      </Head> */}
    ```

2. Disable RSS in `scripts/postbuild.mjs`

    ```
    async function postbuild() {
      // await Promise.all([rss(), sitemap(), search()])
      await Promise.all([sitemap(), search()])
    }    
    ```

**Comment by timlrx** [comment]
Thanks, will have a further look into this one over the next few days

**Comment by timlrx** [comment]
Don't seem to be getting any error from a freshly clone version. You can see an example over at https://github.com/timlrx/test-deployment

**Comment by bravo-kernel** [comment]
Thanks, I will check somewhere this week 💃

**Comment by bravo-kernel** [comment]
Fixed in https://github.com/timlrx/pliny/releases/tag/pliny@0.0.10 👍
